# Generated by Django 3.0 on 2020-01-05 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='server.Base')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('nick_name', models.CharField(max_length=64)),
                ('gender', models.IntegerField(choices=[(0, '男'), (1, '女'), (2, '保密')], default=2)),
                ('phone', models.CharField(blank=True, max_length=16, null=True)),
                ('e_mail', models.CharField(blank=True, max_length=64, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('birth_day', models.CharField(blank=True, max_length=8, null=True)),
                ('city', models.CharField(blank=True, max_length=32, null=True)),
                ('country', models.CharField(blank=True, max_length=64, null=True)),
                ('role', models.IntegerField(choices=[(0, '管理员'), (0, '普通用户')], default=1)),
            ],
            bases=('server.base',),
        ),
    ]
